#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Build Tarball

on:
  pull_request:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+-release"
      - "[0-9]+.[0-9]+.[0-9]+-test"
  push:
    branches:
      - "[0-9]+.[0-9]+.[0-9]+-release"
      - "[0-9]+.[0-9]+.[0-9]+-test"

  workflow_dispatch:

env:
  GH_USERNAME: ${{ secrets.GH_PACKAGE_USER }}
  GH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'maven'
      - name: Build and Package
        run: |
          commitId=`git rev-parse HEAD`
          commitId=${commitId:0:7}
          version=`./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout`
          ./mvnw -T4C -B -q -U -s maven-settings.xml \
            -Drevision=${version}-${commitId} \
            -Dmaven.test.skip \
            -Dcheckstyle.skip=true \
            -Dlicense.skipAddThirdParty=true \
            ${{ github.event.inputs.maven-profiles }} \
            package
      - uses: whaleops/actions/seatunnel/build-and-upload-tar@main
        with:
          oss-config: ${{ secrets.OSS_CONFIG }}
          artifact-pattern: seatunnel-dist/target/apache-seatunnel-*-bin.tar.gz
          build-command: |
            echo "No need to build, already built in previous step"
            ls -alh seatunnel-dist/target
